// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

#import "ACGPBDescriptor.h"
#import "ACGPBMessage.h"
#import "ACGPBRootObject.h"

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ACGPBWrappersRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (ACGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c ACGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
ACGPB_FINAL @interface ACGPBWrappersRoot : ACGPBRootObject
@end

#pragma mark - ACGPBDoubleValue

typedef ACGPB_ENUM(ACGPBDoubleValue_FieldNumber) {
  ACGPBDoubleValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `double`.
 *
 * The JSON representation for `DoubleValue` is JSON number.
 **/
ACGPB_FINAL @interface ACGPBDoubleValue : ACGPBMessage

/** The double value. */
@property(nonatomic, readwrite) double value;

@end

#pragma mark - ACGPBFloatValue

typedef ACGPB_ENUM(ACGPBFloatValue_FieldNumber) {
  ACGPBFloatValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `float`.
 *
 * The JSON representation for `FloatValue` is JSON number.
 **/
ACGPB_FINAL @interface ACGPBFloatValue : ACGPBMessage

/** The float value. */
@property(nonatomic, readwrite) float value;

@end

#pragma mark - ACGPBInt64Value

typedef ACGPB_ENUM(ACGPBInt64Value_FieldNumber) {
  ACGPBInt64Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `int64`.
 *
 * The JSON representation for `Int64Value` is JSON string.
 **/
ACGPB_FINAL @interface ACGPBInt64Value : ACGPBMessage

/** The int64 value. */
@property(nonatomic, readwrite) int64_t value;

@end

#pragma mark - ACGPBUInt64Value

typedef ACGPB_ENUM(ACGPBUInt64Value_FieldNumber) {
  ACGPBUInt64Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `uint64`.
 *
 * The JSON representation for `UInt64Value` is JSON string.
 **/
ACGPB_FINAL @interface ACGPBUInt64Value : ACGPBMessage

/** The uint64 value. */
@property(nonatomic, readwrite) uint64_t value;

@end

#pragma mark - ACGPBInt32Value

typedef ACGPB_ENUM(ACGPBInt32Value_FieldNumber) {
  ACGPBInt32Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `int32`.
 *
 * The JSON representation for `Int32Value` is JSON number.
 **/
ACGPB_FINAL @interface ACGPBInt32Value : ACGPBMessage

/** The int32 value. */
@property(nonatomic, readwrite) int32_t value;

@end

#pragma mark - ACGPBUInt32Value

typedef ACGPB_ENUM(ACGPBUInt32Value_FieldNumber) {
  ACGPBUInt32Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `uint32`.
 *
 * The JSON representation for `UInt32Value` is JSON number.
 **/
ACGPB_FINAL @interface ACGPBUInt32Value : ACGPBMessage

/** The uint32 value. */
@property(nonatomic, readwrite) uint32_t value;

@end

#pragma mark - ACGPBBoolValue

typedef ACGPB_ENUM(ACGPBBoolValue_FieldNumber) {
  ACGPBBoolValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `bool`.
 *
 * The JSON representation for `BoolValue` is JSON `true` and `false`.
 **/
ACGPB_FINAL @interface ACGPBBoolValue : ACGPBMessage

/** The bool value. */
@property(nonatomic, readwrite) BOOL value;

@end

#pragma mark - ACGPBStringValue

typedef ACGPB_ENUM(ACGPBStringValue_FieldNumber) {
  ACGPBStringValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `string`.
 *
 * The JSON representation for `StringValue` is JSON string.
 **/
ACGPB_FINAL @interface ACGPBStringValue : ACGPBMessage

/** The string value. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - ACGPBBytesValue

typedef ACGPB_ENUM(ACGPBBytesValue_FieldNumber) {
  ACGPBBytesValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `bytes`.
 *
 * The JSON representation for `BytesValue` is JSON string.
 **/
ACGPB_FINAL @interface ACGPBBytesValue : ACGPBMessage

/** The bytes value. */
@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
