// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

#import "ACGPBDescriptor.h"
#import "ACGPBMessage.h"
#import "ACGPBRootObject.h"
#import "ACGPBAny.pbobjc.h"
#import "ACGPBSourceContext.pbobjc.h"

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ACGPBEnumValue;
@class ACGPBField;
@class ACGPBOption;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ACGPBSyntax

/** The syntax in which a protocol buffer element is defined. */
typedef ACGPB_ENUM(ACGPBSyntax) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ACGPBSyntax_ACGPBUnrecognizedEnumeratorValue = kACGPBUnrecognizedEnumeratorValue,
  /** Syntax `proto2`. */
  ACGPBSyntax_SyntaxProto2 = 0,

  /** Syntax `proto3`. */
  ACGPBSyntax_SyntaxProto3 = 1,
};

ACGPBEnumDescriptor *ACGPBSyntax_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ACGPBSyntax_IsValidValue(int32_t value);

#pragma mark - Enum ACGPBField_Kind

/** Basic field types. */
typedef ACGPB_ENUM(ACGPBField_Kind) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ACGPBField_Kind_ACGPBUnrecognizedEnumeratorValue = kACGPBUnrecognizedEnumeratorValue,
  /** Field type unknown. */
  ACGPBField_Kind_TypeUnknown = 0,

  /** Field type double. */
  ACGPBField_Kind_TypeDouble = 1,

  /** Field type float. */
  ACGPBField_Kind_TypeFloat = 2,

  /** Field type int64. */
  ACGPBField_Kind_TypeInt64 = 3,

  /** Field type uint64. */
  ACGPBField_Kind_TypeUint64 = 4,

  /** Field type int32. */
  ACGPBField_Kind_TypeInt32 = 5,

  /** Field type fixed64. */
  ACGPBField_Kind_TypeFixed64 = 6,

  /** Field type fixed32. */
  ACGPBField_Kind_TypeFixed32 = 7,

  /** Field type bool. */
  ACGPBField_Kind_TypeBool = 8,

  /** Field type string. */
  ACGPBField_Kind_TypeString = 9,

  /** Field type group. Proto2 syntax only, and deprecated. */
  ACGPBField_Kind_TypeGroup = 10,

  /** Field type message. */
  ACGPBField_Kind_TypeMessage = 11,

  /** Field type bytes. */
  ACGPBField_Kind_TypeBytes = 12,

  /** Field type uint32. */
  ACGPBField_Kind_TypeUint32 = 13,

  /** Field type enum. */
  ACGPBField_Kind_TypeEnum = 14,

  /** Field type sfixed32. */
  ACGPBField_Kind_TypeSfixed32 = 15,

  /** Field type sfixed64. */
  ACGPBField_Kind_TypeSfixed64 = 16,

  /** Field type sint32. */
  ACGPBField_Kind_TypeSint32 = 17,

  /** Field type sint64. */
  ACGPBField_Kind_TypeSint64 = 18,
};

ACGPBEnumDescriptor *ACGPBField_Kind_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ACGPBField_Kind_IsValidValue(int32_t value);

#pragma mark - Enum ACGPBField_Cardinality

/** Whether a field is optional, required, or repeated. */
typedef ACGPB_ENUM(ACGPBField_Cardinality) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ACGPBField_Cardinality_ACGPBUnrecognizedEnumeratorValue = kACGPBUnrecognizedEnumeratorValue,
  /** For fields with unknown cardinality. */
  ACGPBField_Cardinality_CardinalityUnknown = 0,

  /** For optional fields. */
  ACGPBField_Cardinality_CardinalityOptional = 1,

  /** For required fields. Proto2 syntax only. */
  ACGPBField_Cardinality_CardinalityRequired = 2,

  /** For repeated fields. */
  ACGPBField_Cardinality_CardinalityRepeated = 3,
};

ACGPBEnumDescriptor *ACGPBField_Cardinality_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ACGPBField_Cardinality_IsValidValue(int32_t value);

#pragma mark - ACGPBTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (ACGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c ACGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
ACGPB_FINAL @interface ACGPBTypeRoot : ACGPBRootObject
@end

#pragma mark - ACGPBType

typedef ACGPB_ENUM(ACGPBType_FieldNumber) {
  ACGPBType_FieldNumber_Name = 1,
  ACGPBType_FieldNumber_FieldsArray = 2,
  ACGPBType_FieldNumber_OneofsArray = 3,
  ACGPBType_FieldNumber_OptionsArray = 4,
  ACGPBType_FieldNumber_SourceContext = 5,
  ACGPBType_FieldNumber_Syntax = 6,
};

/**
 * A protocol buffer message type.
 **/
ACGPB_FINAL @interface ACGPBType : ACGPBMessage

/** The fully qualified message name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** The list of fields. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACGPBField*> *fieldsArray;
/** The number of items in @c fieldsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

/** The list of types appearing in `oneof` definitions in this type. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *oneofsArray;
/** The number of items in @c oneofsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger oneofsArray_Count;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) ACGPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c ACGPBType's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ACGPBType_Syntax_RawValue(ACGPBType *message);
/**
 * Sets the raw value of an @c ACGPBType's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetACGPBType_Syntax_RawValue(ACGPBType *message, int32_t value);

#pragma mark - ACGPBField

typedef ACGPB_ENUM(ACGPBField_FieldNumber) {
  ACGPBField_FieldNumber_Kind = 1,
  ACGPBField_FieldNumber_Cardinality = 2,
  ACGPBField_FieldNumber_Number = 3,
  ACGPBField_FieldNumber_Name = 4,
  ACGPBField_FieldNumber_TypeURL = 6,
  ACGPBField_FieldNumber_OneofIndex = 7,
  ACGPBField_FieldNumber_Packed = 8,
  ACGPBField_FieldNumber_OptionsArray = 9,
  ACGPBField_FieldNumber_JsonName = 10,
  ACGPBField_FieldNumber_DefaultValue = 11,
};

/**
 * A single field of a message type.
 **/
ACGPB_FINAL @interface ACGPBField : ACGPBMessage

/** The field type. */
@property(nonatomic, readwrite) ACGPBField_Kind kind;

/** The field cardinality. */
@property(nonatomic, readwrite) ACGPBField_Cardinality cardinality;

/** The field number. */
@property(nonatomic, readwrite) int32_t number;

/** The field name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The field type URL, without the scheme, for message or enumeration
 * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeURL;

/**
 * The index of the field type in `Type.oneofs`, for message or enumeration
 * types. The first type has index 1; zero means the type is not in the list.
 **/
@property(nonatomic, readwrite) int32_t oneofIndex;

/** Whether to use alternative packed wire representation. */
@property(nonatomic, readwrite) BOOL packed;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The field JSON name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jsonName;

/** The string value of the default value of this field. Proto2 syntax only. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultValue;

@end

/**
 * Fetches the raw value of a @c ACGPBField's @c kind property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ACGPBField_Kind_RawValue(ACGPBField *message);
/**
 * Sets the raw value of an @c ACGPBField's @c kind property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetACGPBField_Kind_RawValue(ACGPBField *message, int32_t value);

/**
 * Fetches the raw value of a @c ACGPBField's @c cardinality property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ACGPBField_Cardinality_RawValue(ACGPBField *message);
/**
 * Sets the raw value of an @c ACGPBField's @c cardinality property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetACGPBField_Cardinality_RawValue(ACGPBField *message, int32_t value);

#pragma mark - ACGPBEnum

typedef ACGPB_ENUM(ACGPBEnum_FieldNumber) {
  ACGPBEnum_FieldNumber_Name = 1,
  ACGPBEnum_FieldNumber_EnumvalueArray = 2,
  ACGPBEnum_FieldNumber_OptionsArray = 3,
  ACGPBEnum_FieldNumber_SourceContext = 4,
  ACGPBEnum_FieldNumber_Syntax = 5,
};

/**
 * Enum type definition.
 **/
ACGPB_FINAL @interface ACGPBEnum : ACGPBMessage

/** Enum type name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value definitions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACGPBEnumValue*> *enumvalueArray;
/** The number of items in @c enumvalueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger enumvalueArray_Count;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) ACGPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c ACGPBEnum's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ACGPBEnum_Syntax_RawValue(ACGPBEnum *message);
/**
 * Sets the raw value of an @c ACGPBEnum's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetACGPBEnum_Syntax_RawValue(ACGPBEnum *message, int32_t value);

#pragma mark - ACGPBEnumValue

typedef ACGPB_ENUM(ACGPBEnumValue_FieldNumber) {
  ACGPBEnumValue_FieldNumber_Name = 1,
  ACGPBEnumValue_FieldNumber_Number = 2,
  ACGPBEnumValue_FieldNumber_OptionsArray = 3,
};

/**
 * Enum value definition.
 **/
ACGPB_FINAL @interface ACGPBEnumValue : ACGPBMessage

/** Enum value name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value number. */
@property(nonatomic, readwrite) int32_t number;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

@end

#pragma mark - ACGPBOption

typedef ACGPB_ENUM(ACGPBOption_FieldNumber) {
  ACGPBOption_FieldNumber_Name = 1,
  ACGPBOption_FieldNumber_Value = 2,
};

/**
 * A protocol buffer option, which can be attached to a message, field,
 * enumeration, etc.
 **/
ACGPB_FINAL @interface ACGPBOption : ACGPBMessage

/**
 * The option's name. For protobuf built-in options (options defined in
 * descriptor.proto), this is the short name. For example, `"map_entry"`.
 * For custom options, it should be the fully-qualified name. For example,
 * `"google.api.http"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The option's value packed in an Any message. If the value is a primitive,
 * the corresponding wrapper type defined in google/protobuf/wrappers.proto
 * should be used. If the value is an enum, it should be stored as an int32
 * value using the google.protobuf.Int32Value type.
 **/
@property(nonatomic, readwrite, strong, null_resettable) ACGPBAny *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
