// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acpb.user.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/ACGPBProtocolBuffers.h>
#else
 #import "ACGPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ACPBSysConfigItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AcpbUserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (ACGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c ACGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
ACGPB_FINAL @interface AcpbUserRoot : ACGPBRootObject
@end

#pragma mark - ACPBUserFrozenToLoginResp

typedef ACGPB_ENUM(ACPBUserFrozenToLoginResp_FieldNumber) {
  ACPBUserFrozenToLoginResp_FieldNumber_ErrorCode = 1,
  ACPBUserFrozenToLoginResp_FieldNumber_ErrorMessage = 2,
  ACPBUserFrozenToLoginResp_FieldNumber_FrozenType = 3,
  ACPBUserFrozenToLoginResp_FieldNumber_ForceLogoutDeleteAllLocalMessagesFlag = 4,
};

/**
 * 封号主动推送
 **/
ACGPB_FINAL @interface ACPBUserFrozenToLoginResp : ACGPBMessage

/** UserFrozenToLoginRespCmdId = 0x30018FFF; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** 封号级别 */
@property(nonatomic, readwrite) int32_t frozenType;

/** 踢人下线删除 默认为不删除 false */
@property(nonatomic, readwrite) BOOL forceLogoutDeleteAllLocalMessagesFlag;

@end

#pragma mark - ACPBGetUserOnlineTimeReq

typedef ACGPB_ENUM(ACPBGetUserOnlineTimeReq_FieldNumber) {
  ACPBGetUserOnlineTimeReq_FieldNumber_DestId = 1,
};

/**
 * 获取用户最后在线时间
 **/
ACGPB_FINAL @interface ACPBGetUserOnlineTimeReq : ACGPBMessage

/** GetUserOnlineTimeReqCmdId = 0x3011102D; */
@property(nonatomic, readwrite) int64_t destId;

@end

#pragma mark - ACPBGetUserOnlineTimeResp

typedef ACGPB_ENUM(ACPBGetUserOnlineTimeResp_FieldNumber) {
  ACPBGetUserOnlineTimeResp_FieldNumber_ErrorCode = 1,
  ACPBGetUserOnlineTimeResp_FieldNumber_ErrorMessage = 2,
  ACPBGetUserOnlineTimeResp_FieldNumber_Onlinestatus = 3,
  ACPBGetUserOnlineTimeResp_FieldNumber_LastOnlineTime = 4,
};

ACGPB_FINAL @interface ACPBGetUserOnlineTimeResp : ACGPBMessage

/** GetUserOnlineTimeRespCmdId = 0x3011802D; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** 在线状态 1是在线;2是在30秒前在线就显示最后在线时间,离线;3对方关闭在线输入和在线状态开关;4表示未知 */
@property(nonatomic, readwrite) int32_t onlinestatus;

/** 最后在线时间 onlinestatus为2的时候 用来显示 */
@property(nonatomic, readwrite) int64_t lastOnlineTime;

@end

#pragma mark - ACPBUpdatePushConfigReq

typedef ACGPB_ENUM(ACPBUpdatePushConfigReq_FieldNumber) {
  ACPBUpdatePushConfigReq_FieldNumber_Content = 1,
};

/**
 * push设置
 **/
ACGPB_FINAL @interface ACPBUpdatePushConfigReq : ACGPBMessage

/**
 *
 * config json string
 *
 * lan: 推送语言(zh_CN、en_US)
 * preview: 推送是否显示详情(0:否 1:是)
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - ACPBUpdatePushConfigResp

typedef ACGPB_ENUM(ACPBUpdatePushConfigResp_FieldNumber) {
  ACPBUpdatePushConfigResp_FieldNumber_ErrorCode = 1,
  ACPBUpdatePushConfigResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBUpdatePushConfigResp : ACGPBMessage

@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBGetPushConfigResp

typedef ACGPB_ENUM(ACPBGetPushConfigResp_FieldNumber) {
  ACPBGetPushConfigResp_FieldNumber_ErrorCode = 1,
  ACPBGetPushConfigResp_FieldNumber_ErrorMessage = 2,
  ACPBGetPushConfigResp_FieldNumber_Content = 3,
};

/**
 * 获取push设置
 **/
ACGPB_FINAL @interface ACPBGetPushConfigResp : ACGPBMessage

@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - ACPBUpdateBlockContactsReq

typedef ACGPB_ENUM(ACPBUpdateBlockContactsReq_FieldNumber) {
  ACPBUpdateBlockContactsReq_FieldNumber_DestIdsArray = 1,
  ACPBUpdateBlockContactsReq_FieldNumber_BlockFlag = 2,
};

/**
 * 把联系人加入或者取消黑名单
 **/
ACGPB_FINAL @interface ACPBUpdateBlockContactsReq : ACGPBMessage

/** UpdateBlockContactsReqCmdId= 0x40011004 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBInt64Array *destIdsArray;
/** The number of items in @c destIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger destIdsArray_Count;

/** 加入黑名单为true,取消为false */
@property(nonatomic, readwrite) BOOL blockFlag;

@end

#pragma mark - ACPBUpdateBlockContactsResp

typedef ACGPB_ENUM(ACPBUpdateBlockContactsResp_FieldNumber) {
  ACPBUpdateBlockContactsResp_FieldNumber_ErrorCode = 1,
  ACPBUpdateBlockContactsResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBUpdateBlockContactsResp : ACGPBMessage

/** UpdateBlockContactsRespCmdId= 0x40011004 */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBGetBlocksReq

typedef ACGPB_ENUM(ACPBGetBlocksReq_FieldNumber) {
  ACPBGetBlocksReq_FieldNumber_DestIdArray = 1,
};

/**
 * 查询黑名单列表
 **/
ACGPB_FINAL @interface ACPBGetBlocksReq : ACGPBMessage

/** GetBlocksReqCmdId= 0x40021006 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBInt64Array *destIdArray;
/** The number of items in @c destIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger destIdArray_Count;

@end

#pragma mark - ACPBGetBlocksResp

typedef ACGPB_ENUM(ACPBGetBlocksResp_FieldNumber) {
  ACPBGetBlocksResp_FieldNumber_ErrorCode = 1,
  ACPBGetBlocksResp_FieldNumber_ErrorMessage = 2,
  ACPBGetBlocksResp_FieldNumber_DestIdsArray = 3,
};

ACGPB_FINAL @interface ACPBGetBlocksResp : ACGPBMessage

/** GetBlocksRespCmdId= 0x40028007 */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** 用户 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBInt64Array *destIdsArray;
/** The number of items in @c destIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger destIdsArray_Count;

@end

#pragma mark - ACPBGetSysConfigReq

/**
 * 获取oss配置，声网key
 **/
ACGPB_FINAL @interface ACPBGetSysConfigReq : ACGPBMessage

@end

#pragma mark - ACPBGetSysConfigResp

typedef ACGPB_ENUM(ACPBGetSysConfigResp_FieldNumber) {
  ACPBGetSysConfigResp_FieldNumber_ErrorCode = 1,
  ACPBGetSysConfigResp_FieldNumber_ErrorMessage = 2,
  ACPBGetSysConfigResp_FieldNumber_ConfigArray = 3,
};

ACGPB_FINAL @interface ACPBGetSysConfigResp : ACGPBMessage

/** 0x40018014 */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/**
 * 配置项
 * 声网： key="agora" value="声网key"
 * oss :  key="alioss" value={ed":"endPoint","ak":"accessKey","as":"accessSecret","bk":"桶名"}
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACPBSysConfigItem*> *configArray;
/** The number of items in @c configArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger configArray_Count;

@end

#pragma mark - ACPBSysConfigItem

typedef ACGPB_ENUM(ACPBSysConfigItem_FieldNumber) {
  ACPBSysConfigItem_FieldNumber_Key = 1,
  ACPBSysConfigItem_FieldNumber_Value = 2,
};

/**
 * user configuration item
 **/
ACGPB_FINAL @interface ACPBSysConfigItem : ACGPBMessage

/** configuration key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

/** configuration value */
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
