// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acpb.supergroupchat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/ACGPBProtocolBuffers.h>
#else
 #import "ACGPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ACPBDialogMessageList;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AcpbSupergroupchatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (ACGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c ACGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
ACGPB_FINAL @interface AcpbSupergroupchatRoot : ACGPBRootObject
@end

#pragma mark - ACPBSendSuperGroupMessageResp

typedef ACGPB_ENUM(ACPBSendSuperGroupMessageResp_FieldNumber) {
  ACPBSendSuperGroupMessageResp_FieldNumber_DialogKey = 1,
  ACPBSendSuperGroupMessageResp_FieldNumber_Msg = 2,
};

/**
 * 服务器端主动推送超级群新消息  0x6002819c
 **/
ACGPB_FINAL @interface ACPBSendSuperGroupMessageResp : ACGPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *dialogKey;

@property(nonatomic, readwrite, strong, null_resettable) ACPBDialogMessageList *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - ACPBGetSuperGroupNewMessageReq

typedef ACGPB_ENUM(ACPBGetSuperGroupNewMessageReq_FieldNumber) {
  ACPBGetSuperGroupNewMessageReq_FieldNumber_DialogKeys = 1,
  ACPBGetSuperGroupNewMessageReq_FieldNumber_Offset = 2,
  ACPBGetSuperGroupNewMessageReq_FieldNumber_ReadOffsets = 3,
};

/**
 * 获取超级群离线消息请求 0x6002815c
 **/
ACGPB_FINAL @interface ACPBGetSuperGroupNewMessageReq : ACGPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ACGPBStringInt64Dictionary *dialogKeys;
/** The number of items in @c dialogKeys without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dialogKeys_Count;

/** 客户端持有的最新消息序号偏移量 */
@property(nonatomic, readwrite) int64_t offset;

/** 读偏移 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBStringInt64Dictionary *readOffsets;
/** The number of items in @c readOffsets without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger readOffsets_Count;

@end

#pragma mark - ACPBGetSuperGroupNewMessageResp

typedef ACGPB_ENUM(ACPBGetSuperGroupNewMessageResp_FieldNumber) {
  ACPBGetSuperGroupNewMessageResp_FieldNumber_ErrorCode = 1,
  ACPBGetSuperGroupNewMessageResp_FieldNumber_ErrorMessage = 2,
  ACPBGetSuperGroupNewMessageResp_FieldNumber_Msg = 3,
  ACPBGetSuperGroupNewMessageResp_FieldNumber_MsgEnd = 4,
  ACPBGetSuperGroupNewMessageResp_FieldNumber_UnreadCounts = 5,
  ACPBGetSuperGroupNewMessageResp_FieldNumber_ReadOffsets = 6,
};

/**
 * 获取超级群离线消息响应  0x6002816c
 **/
ACGPB_FINAL @interface ACPBGetSuperGroupNewMessageResp : ACGPBMessage

@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** map<destId, DialogMessageList> 有新消息的会话对应的消息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, ACPBDialogMessageList*> *msg;
/** The number of items in @c msg without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msg_Count;

/** 表示会话有没有更多的消息 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBStringBoolDictionary *msgEnd;
/** The number of items in @c msgEnd without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgEnd_Count;

/** 会话未读数 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBStringInt32Dictionary *unreadCounts;
/** The number of items in @c unreadCounts without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger unreadCounts_Count;

/** 会话最新读偏移 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBStringInt64Dictionary *readOffsets;
/** The number of items in @c readOffsets without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger readOffsets_Count;

@end

#pragma mark - ACPBClearSuperGroupUnreadStatusReq

typedef ACGPB_ENUM(ACPBClearSuperGroupUnreadStatusReq_FieldNumber) {
  ACPBClearSuperGroupUnreadStatusReq_FieldNumber_DialogId = 1,
  ACPBClearSuperGroupUnreadStatusReq_FieldNumber_ReadOffset = 2,
};

/**
 * 清除某个会话中的未读消息数请求（该会话在时间戳 timestamp 之前的消息将被置成已读。） 0x6002822c
 **/
ACGPB_FINAL @interface ACPBClearSuperGroupUnreadStatusReq : ACGPBMessage

/** 会话id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *dialogId;

/** 最新已读的偏移 */
@property(nonatomic, readwrite) int64_t readOffset;

@end

#pragma mark - ACPBClearSuperGroupUnreadStatusResp

typedef ACGPB_ENUM(ACPBClearSuperGroupUnreadStatusResp_FieldNumber) {
  ACPBClearSuperGroupUnreadStatusResp_FieldNumber_ErrorCode = 1,
  ACPBClearSuperGroupUnreadStatusResp_FieldNumber_ErrorMessage = 2,
};

/**
 * 清除某个会话中的未读消息数响应 0x6002823c
 **/
ACGPB_FINAL @interface ACPBClearSuperGroupUnreadStatusResp : ACGPBMessage

@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
