// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acpb.groupchat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if ACGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/ACGPBProtocolBuffers.h>
#else
 #import "ACGPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ACPBDialogMessage;
@class ACPBGroupChatMessage;
@class ACPBGroupMember;
@class ACPBReferenceDialogMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AcpbGroupchatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (ACGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c ACGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
ACGPB_FINAL @interface AcpbGroupchatRoot : ACGPBRootObject
@end

#pragma mark - ACPBGroupMember

typedef ACGPB_ENUM(ACPBGroupMember_FieldNumber) {
  ACPBGroupMember_FieldNumber_MemberUid = 1,
  ACPBGroupMember_FieldNumber_MemberName = 2,
  ACPBGroupMember_FieldNumber_MemberAlias = 3,
  ACPBGroupMember_FieldNumber_MemberSmallAvatarURL = 4,
  ACPBGroupMember_FieldNumber_ReferenceUid = 5,
  ACPBGroupMember_FieldNumber_JoinTime = 6,
  ACPBGroupMember_FieldNumber_Admin = 7,
};

/**
 * 群成员
 **/
ACGPB_FINAL @interface ACPBGroupMember : ACGPBMessage

/** 成员的uid */
@property(nonatomic, readwrite) int64_t memberUid;

/** 成员的uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberName;

/** 成员自己设置的在该群的别名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberAlias;

/** 成员的头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberSmallAvatarURL;

/** 由谁拉入群 */
@property(nonatomic, readwrite) int64_t referenceUid;

/** 加入时间 */
@property(nonatomic, readwrite) int64_t joinTime;

/** 是否为管理员 */
@property(nonatomic, readwrite) BOOL admin;

@end

#pragma mark - ACPBSendGroupChatMessageReq

typedef ACGPB_ENUM(ACPBSendGroupChatMessageReq_FieldNumber) {
  ACPBSendGroupChatMessageReq_FieldNumber_GroupId = 1,
  ACPBSendGroupChatMessageReq_FieldNumber_LocalId = 2,
  ACPBSendGroupChatMessageReq_FieldNumber_MsgPreContent = 3,
  ACPBSendGroupChatMessageReq_FieldNumber_MsgPostContent = 4,
  ACPBSendGroupChatMessageReq_FieldNumber_MediaFlag = 5,
  ACPBSendGroupChatMessageReq_FieldNumber_MediaConstructor = 6,
  ACPBSendGroupChatMessageReq_FieldNumber_MediaAttribute = 7,
  ACPBSendGroupChatMessageReq_FieldNumber_AtArray = 8,
  ACPBSendGroupChatMessageReq_FieldNumber_Extra = 9,
  ACPBSendGroupChatMessageReq_FieldNumber_Assign = 10,
  ACPBSendGroupChatMessageReq_FieldNumber_AtAll = 11,
  ACPBSendGroupChatMessageReq_FieldNumber_MsgContent = 12,
  ACPBSendGroupChatMessageReq_FieldNumber_PushContent = 13,
  ACPBSendGroupChatMessageReq_FieldNumber_IsBackEnd = 14,
  ACPBSendGroupChatMessageReq_FieldNumber_IsNotIncludeSender = 15,
  ACPBSendGroupChatMessageReq_FieldNumber_ObjectName = 16,
  ACPBSendGroupChatMessageReq_FieldNumber_Save = 17,
};

/**
 * 发送消息 请求
 **/
ACGPB_FINAL @interface ACPBSendGroupChatMessageReq : ACGPBMessage

/** SendGroupChatMessageReqCmdId= 0x60021001; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** app端分配的消息id */
@property(nonatomic, readwrite) int64_t localId;

/** 前置消息的内容 (如果没有多媒体内容，preContent传空值，) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgPreContent;

/** 后置消息的内容 (如果没有多媒体内容，请使用这个字段) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgPostContent;

/** 是否有多媒体内容 */
@property(nonatomic, readwrite) BOOL mediaFlag;

/** 消息中包涵的多媒体类型 */
@property(nonatomic, readwrite) int32_t mediaConstructor;

/** 多媒体属性的JSON格式 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaAttribute;

/** \@用户列表 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBInt64Array *atArray;
/** The number of items in @c atArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger atArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

/** 给指定用户发消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *assign;

/** 是否at all */
@property(nonatomic, readwrite) BOOL atAll;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushContent;

/** 是否是后端发起的，后端发起的，不判断用户是否在群里 */
@property(nonatomic, readwrite) BOOL isBackEnd;

/** 消息发送者是否可在客户端接收该消息 */
@property(nonatomic, readwrite) BOOL isNotIncludeSender;

/** 消息类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *objectName;

/** 是否需要保存到db */
@property(nonatomic, readwrite) BOOL save;

@end

#pragma mark - ACPBSendGroupChatMessageResp

typedef ACGPB_ENUM(ACPBSendGroupChatMessageResp_FieldNumber) {
  ACPBSendGroupChatMessageResp_FieldNumber_ErrorCode = 1,
  ACPBSendGroupChatMessageResp_FieldNumber_ErrorMessage = 2,
  ACPBSendGroupChatMessageResp_FieldNumber_LocalId = 3,
  ACPBSendGroupChatMessageResp_FieldNumber_MsgId = 4,
  ACPBSendGroupChatMessageResp_FieldNumber_MsgSendTime = 5,
  ACPBSendGroupChatMessageResp_FieldNumber_Seqno = 6,
};

/**
 * 发送消息 回复
 **/
ACGPB_FINAL @interface ACPBSendGroupChatMessageResp : ACGPBMessage

/** SendGroupChatMessageRespCmdId=0x60028001; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** app端分配的消息id */
@property(nonatomic, readwrite) int64_t localId;

/** 服务器端消息id */
@property(nonatomic, readwrite) int64_t msgId;

/** 服务器端记录的消息发送时间 */
@property(nonatomic, readwrite) int64_t msgSendTime;

/** 游标 */
@property(nonatomic, readwrite) int64_t seqno;

@end

#pragma mark - ACPBReplyGroupChatMessageReq

typedef ACGPB_ENUM(ACPBReplyGroupChatMessageReq_FieldNumber) {
  ACPBReplyGroupChatMessageReq_FieldNumber_GroupId = 1,
  ACPBReplyGroupChatMessageReq_FieldNumber_LocalId = 2,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgPreContent = 3,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgPostContent = 4,
  ACPBReplyGroupChatMessageReq_FieldNumber_MediaFlag = 5,
  ACPBReplyGroupChatMessageReq_FieldNumber_MediaConstructor = 6,
  ACPBReplyGroupChatMessageReq_FieldNumber_MediaAttribute = 7,
  ACPBReplyGroupChatMessageReq_FieldNumber_AtArray = 8,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgIdReferenced = 9,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgSrcIdReferenced = 10,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgDestIdReferenced = 11,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgPreContentReferenced = 12,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgPostContentReferenced = 13,
  ACPBReplyGroupChatMessageReq_FieldNumber_MediaFlagReferenced = 14,
  ACPBReplyGroupChatMessageReq_FieldNumber_MediaConstructorReferenced = 15,
  ACPBReplyGroupChatMessageReq_FieldNumber_MediaAttributeReferenced = 16,
  ACPBReplyGroupChatMessageReq_FieldNumber_MsgSendTimeReferenced = 17,
};

/**
 * 群聊reply消息 请求
 **/
ACGPB_FINAL @interface ACPBReplyGroupChatMessageReq : ACGPBMessage

/** ReplyGroupChatMessageReqCmdId=0x60021002; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** app端分配的消息id */
@property(nonatomic, readwrite) int64_t localId;

/** 前置消息的内容 (如果没有多媒体内容，preContent传空值，) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgPreContent;

/** 后置消息的内容 (如果没有多媒体内容，请使用这个字段) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgPostContent;

/** 是否有多媒体内容 */
@property(nonatomic, readwrite) BOOL mediaFlag;

/** 消息中包涵的多媒体类型 */
@property(nonatomic, readwrite) int32_t mediaConstructor;

/** 取值为相应的SGMediaObject其constructor */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaAttribute;

/** \@用户列表 */
@property(nonatomic, readwrite, strong, null_resettable) ACGPBInt64Array *atArray;
/** The number of items in @c atArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger atArray_Count;

/** 引用消息的id */
@property(nonatomic, readwrite) int64_t msgIdReferenced;

/** 引用消息的发件人id */
@property(nonatomic, readwrite) int64_t msgSrcIdReferenced;

/** 引用消息的收件人id */
@property(nonatomic, readwrite) int64_t msgDestIdReferenced;

/** 前置消息的内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgPreContentReferenced;

/** (如果没有多媒体内容，preContent传空值，) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgPostContentReferenced;

/** 是否有多媒体内容 */
@property(nonatomic, readwrite) BOOL mediaFlagReferenced;

/** 消息中包涵的多媒体类型 */
@property(nonatomic, readwrite) int32_t mediaConstructorReferenced;

/** 取值为相应的SGMediaObject其constructor */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaAttributeReferenced;

/** 引用消息的发送时间 */
@property(nonatomic, readwrite) int64_t msgSendTimeReferenced;

@end

#pragma mark - ACPBReplyGroupChatMessageResp

typedef ACGPB_ENUM(ACPBReplyGroupChatMessageResp_FieldNumber) {
  ACPBReplyGroupChatMessageResp_FieldNumber_ErrorCode = 1,
  ACPBReplyGroupChatMessageResp_FieldNumber_ErrorMessage = 2,
  ACPBReplyGroupChatMessageResp_FieldNumber_LocalId = 3,
  ACPBReplyGroupChatMessageResp_FieldNumber_MsgId = 4,
  ACPBReplyGroupChatMessageResp_FieldNumber_MsgSendTime = 5,
};

/**
 * 群聊reply消息  回复
 **/
ACGPB_FINAL @interface ACPBReplyGroupChatMessageResp : ACGPBMessage

/** ReplyGroupChatMessageRespCmdId=0x60028002; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** app端分配的消息id */
@property(nonatomic, readwrite) int64_t localId;

/** 服务器端消息id */
@property(nonatomic, readwrite) int64_t msgId;

/** 服务器端记录的发送时间戳 */
@property(nonatomic, readwrite) int64_t msgSendTime;

@end

#pragma mark - ACPBGetGroupChatDialogDetailNewReq

typedef ACGPB_ENUM(ACPBGetGroupChatDialogDetailNewReq_FieldNumber) {
  ACPBGetGroupChatDialogDetailNewReq_FieldNumber_GroupId = 1,
};

/**
 * 获取群详情  请求
 **/
ACGPB_FINAL @interface ACPBGetGroupChatDialogDetailNewReq : ACGPBMessage

/** GetGroupChatDialogDetailNewReqCmdId=0x6002101E; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - ACPBGetGroupChatDialogDetailNewResp

typedef ACGPB_ENUM(ACPBGetGroupChatDialogDetailNewResp_FieldNumber) {
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_ErrorCode = 1,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_ErrorMessage = 2,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_GroupId = 3,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_AdminId = 4,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_IsUntitled = 5,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_GroupTitle = 6,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_AnnouncementContent = 7,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_AnnouncementPostTime = 8,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_AnnouncementPostId = 9,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_AnnouncementPostUserSmallAvatarURL = 10,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_SmallAvatarURL = 11,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_OriginalAvatarURL = 12,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_QrcodeString = 13,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_StickyFlag = 14,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_MuteFlag = 15,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_BlockFlag = 16,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_BurnAfterReadingFlag = 17,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_GroupAuthFlag = 18,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_GroupContactFlag = 19,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_TotalMemberNumber = 20,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_GroupMemberArray = 21,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_TakeScreenshotFlag = 22,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_GroupMessageLifetimeFlag = 23,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_GroupMessageLifetime = 24,
  ACPBGetGroupChatDialogDetailNewResp_FieldNumber_BurnAfterReadingTime = 25,
};

/**
 * 获取群详情  回复
 **/
ACGPB_FINAL @interface ACPBGetGroupChatDialogDetailNewResp : ACGPBMessage

/** GetGroupChatDialogDetailNewRespCmdId=0x6002801E; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** 群id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 管理员id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *adminId;

/** 该群是否有命名 */
@property(nonatomic, readwrite) BOOL isUntitled;

/** 群名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupTitle;

/** 群公告内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *announcementContent;

/** 群公告更新时间 */
@property(nonatomic, readwrite) int64_t announcementPostTime;

/** 群公告修改人uid */
@property(nonatomic, readwrite) int64_t announcementPostId;

/** 群公告修改人头像缩略图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *announcementPostUserSmallAvatarURL;

/** 头像缩略图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *smallAvatarURL;

/** 头像原图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *originalAvatarURL;

/** 二维码缩略图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *qrcodeString;

/** 是否置顶 */
@property(nonatomic, readwrite) BOOL stickyFlag;

/** 是否免打扰 */
@property(nonatomic, readwrite) BOOL muteFlag;

/** 是否拉黑 */
@property(nonatomic, readwrite) BOOL blockFlag;

/** 是否阅后即焚 */
@property(nonatomic, readwrite) BOOL burnAfterReadingFlag;

/** 是否开启群认证 */
@property(nonatomic, readwrite) BOOL groupAuthFlag;

/** 群是否保存到通讯录 */
@property(nonatomic, readwrite) BOOL groupContactFlag;

/** 群成员总共人数 */
@property(nonatomic, readwrite) int32_t totalMemberNumber;

/** string memberInfo=21; // 群成员信息 List<GroupMember>对应的JSON串 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACPBGroupMember*> *groupMemberArray;
/** The number of items in @c groupMemberArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupMemberArray_Count;

/** 是否开启截屏通知 */
@property(nonatomic, readwrite) BOOL takeScreenshotFlag;

/** 群消息有效期开关 (true为开启 false为关闭) */
@property(nonatomic, readwrite) BOOL groupMessageLifetimeFlag;

/** 群消息有效期 (单位 ms 默认为0永远不过期) */
@property(nonatomic, readwrite) int64_t groupMessageLifetime;

/** 当burnAfterReadingFlag为true的时候才有意义,阅后即焚时间 */
@property(nonatomic, readwrite) int64_t burnAfterReadingTime;

@end

#pragma mark - ACPBDeleteGroupChatHistoryReq

typedef ACGPB_ENUM(ACPBDeleteGroupChatHistoryReq_FieldNumber) {
  ACPBDeleteGroupChatHistoryReq_FieldNumber_GroupId = 1,
};

/**
 * 删除历史消息 请求
 **/
ACGPB_FINAL @interface ACPBDeleteGroupChatHistoryReq : ACGPBMessage

/** DeleteGroupChatHistoryReqCmdId=0x6002100E; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - ACPBDeleteGroupChatHistoryResp

typedef ACGPB_ENUM(ACPBDeleteGroupChatHistoryResp_FieldNumber) {
  ACPBDeleteGroupChatHistoryResp_FieldNumber_ErrorCode = 1,
  ACPBDeleteGroupChatHistoryResp_FieldNumber_ErrorMessage = 2,
};

/**
 * 删除历史消息 回复
 **/
ACGPB_FINAL @interface ACPBDeleteGroupChatHistoryResp : ACGPBMessage

/** DeleteGroupChatHistoryRespCmdId=0x6002800E; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBUpdateGroupChatDialogStickyConfigReq

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogStickyConfigReq_FieldNumber) {
  ACPBUpdateGroupChatDialogStickyConfigReq_FieldNumber_GroupId = 1,
  ACPBUpdateGroupChatDialogStickyConfigReq_FieldNumber_StickyFlag = 2,
};

/**
 * 置顶设置 请求
 **/
ACGPB_FINAL @interface ACPBUpdateGroupChatDialogStickyConfigReq : ACGPBMessage

/** UpdateGroupChatDialogStickyConfigReqCmdId=0x6002100A; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 是否置顶 */
@property(nonatomic, readwrite) BOOL stickyFlag;

@end

#pragma mark - ACPBUpdateGroupChatDialogStickyConfigResp

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogStickyConfigResp_FieldNumber) {
  ACPBUpdateGroupChatDialogStickyConfigResp_FieldNumber_ErrorCode = 1,
  ACPBUpdateGroupChatDialogStickyConfigResp_FieldNumber_ErrorMessage = 2,
};

/**
 * 置顶设置 回复
 **/
ACGPB_FINAL @interface ACPBUpdateGroupChatDialogStickyConfigResp : ACGPBMessage

/** UpdateGroupChatDialogStickyConfigRespCmdId=0x6002800A; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBUpdateGroupChatDialogMuteConfigReq

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogMuteConfigReq_FieldNumber) {
  ACPBUpdateGroupChatDialogMuteConfigReq_FieldNumber_GroupId = 1,
  ACPBUpdateGroupChatDialogMuteConfigReq_FieldNumber_MuteFlag = 2,
};

/**
 * 静音设置  请求
 **/
ACGPB_FINAL @interface ACPBUpdateGroupChatDialogMuteConfigReq : ACGPBMessage

/** UpdateGroupChatDialogMuteConfigReqCmdId= 0x6002100B; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 是否静音 */
@property(nonatomic, readwrite) BOOL muteFlag;

@end

#pragma mark - ACPBUpdateGroupChatDialogMuteConfigResp

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogMuteConfigResp_FieldNumber) {
  ACPBUpdateGroupChatDialogMuteConfigResp_FieldNumber_ErrorCode = 1,
  ACPBUpdateGroupChatDialogMuteConfigResp_FieldNumber_ErrorMessage = 2,
};

/**
 * 静音设置 回复
 **/
ACGPB_FINAL @interface ACPBUpdateGroupChatDialogMuteConfigResp : ACGPBMessage

/** UpdateGroupChatDialogMuteConfigRespCmdId= 0x6002800B; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBUpdateGroupChatDialogNotificationLevelReq

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogNotificationLevelReq_FieldNumber) {
  ACPBUpdateGroupChatDialogNotificationLevelReq_FieldNumber_DestIdArray = 1,
  ACPBUpdateGroupChatDialogNotificationLevelReq_FieldNumber_MuteFlag = 2,
};

/**
 * 免打扰等级设置
 **/
ACGPB_FINAL @interface ACPBUpdateGroupChatDialogNotificationLevelReq : ACGPBMessage

/** 0x60018035 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *destIdArray;
/** The number of items in @c destIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger destIdArray_Count;

/** -1接收全部通知 0初始状态 2接收被\@通知 4接收\@全体成员通知 5不接收通知 */
@property(nonatomic, readwrite) int32_t muteFlag;

@end

#pragma mark - ACPBUpdateGroupChatDialogNotificationLevelResp

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogNotificationLevelResp_FieldNumber) {
  ACPBUpdateGroupChatDialogNotificationLevelResp_FieldNumber_ErrorCode = 1,
  ACPBUpdateGroupChatDialogNotificationLevelResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBUpdateGroupChatDialogNotificationLevelResp : ACGPBMessage

/** 0x6001802B */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBUpdateGroupChatDialogBlockConfigReq

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogBlockConfigReq_FieldNumber) {
  ACPBUpdateGroupChatDialogBlockConfigReq_FieldNumber_GroupId = 1,
  ACPBUpdateGroupChatDialogBlockConfigReq_FieldNumber_BlockFlag = 2,
};

/**
 * 拉黑设置 请求
 **/
ACGPB_FINAL @interface ACPBUpdateGroupChatDialogBlockConfigReq : ACGPBMessage

/** UpdateGroupChatDialogBlockConfigReqCmdId= 0x6002100C; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 是否拉黑 */
@property(nonatomic, readwrite) BOOL blockFlag;

@end

#pragma mark - ACPBUpdateGroupChatDialogBlockConfigResp

typedef ACGPB_ENUM(ACPBUpdateGroupChatDialogBlockConfigResp_FieldNumber) {
  ACPBUpdateGroupChatDialogBlockConfigResp_FieldNumber_ErrorCode = 1,
  ACPBUpdateGroupChatDialogBlockConfigResp_FieldNumber_ErrorMessage = 2,
};

/**
 * 拉黑设置 回复
 **/
ACGPB_FINAL @interface ACPBUpdateGroupChatDialogBlockConfigResp : ACGPBMessage

/** UpdateGroupChatDialogBlockConfigRespCmdId= 0x6002800C; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBRecallGroupChatMessageReq

typedef ACGPB_ENUM(ACPBRecallGroupChatMessageReq_FieldNumber) {
  ACPBRecallGroupChatMessageReq_FieldNumber_GroupId = 1,
  ACPBRecallGroupChatMessageReq_FieldNumber_MsgId = 2,
};

/**
 * 撤回消息 请求
 **/
ACGPB_FINAL @interface ACPBRecallGroupChatMessageReq : ACGPBMessage

/** RecallGroupChatMessageReqCmdId = 0x6002102B; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 待删除的消息id */
@property(nonatomic, readwrite) int64_t msgId;

@end

#pragma mark - ACPBRecallGroupChatMessageResp

typedef ACGPB_ENUM(ACPBRecallGroupChatMessageResp_FieldNumber) {
  ACPBRecallGroupChatMessageResp_FieldNumber_ErrorCode = 1,
  ACPBRecallGroupChatMessageResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBRecallGroupChatMessageResp : ACGPBMessage

/** RecallGroupChatMessageRespCmdId = 0x6002802B; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBStartTypingGroupChatReq

typedef ACGPB_ENUM(ACPBStartTypingGroupChatReq_FieldNumber) {
  ACPBStartTypingGroupChatReq_FieldNumber_GroupId = 1,
};

/**
 * 群聊正在输入-开始
 **/
ACGPB_FINAL @interface ACPBStartTypingGroupChatReq : ACGPBMessage

/** StartTypingGroupChatReqCmdId = 0x6002102C; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - ACPBStartTypingGroupChatResp

typedef ACGPB_ENUM(ACPBStartTypingGroupChatResp_FieldNumber) {
  ACPBStartTypingGroupChatResp_FieldNumber_ErrorCode = 1,
  ACPBStartTypingGroupChatResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBStartTypingGroupChatResp : ACGPBMessage

/** StartTypingGroupChatRespCmdId = 0x6002802C; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBEndTypingGroupChatReq

typedef ACGPB_ENUM(ACPBEndTypingGroupChatReq_FieldNumber) {
  ACPBEndTypingGroupChatReq_FieldNumber_GroupId = 1,
};

/**
 * 群聊正在输入-结束
 **/
ACGPB_FINAL @interface ACPBEndTypingGroupChatReq : ACGPBMessage

/** EndTypingGroupChatReqCmdId = 0x6002102D; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - ACPBEndTypingGroupChatResp

typedef ACGPB_ENUM(ACPBEndTypingGroupChatResp_FieldNumber) {
  ACPBEndTypingGroupChatResp_FieldNumber_ErrorCode = 1,
  ACPBEndTypingGroupChatResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBEndTypingGroupChatResp : ACGPBMessage

/** EndTypingGroupChatRespCmdId = 0x6002802D; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBGroupChatMessage

typedef ACGPB_ENUM(ACPBGroupChatMessage_FieldNumber) {
  ACPBGroupChatMessage_FieldNumber_GroupId = 1,
  ACPBGroupChatMessage_FieldNumber_UserId = 2,
  ACPBGroupChatMessage_FieldNumber_MsgIdArray = 3,
};

/**
 * 封装群id 发消息者id 消息id列表
 **/
ACGPB_FINAL @interface ACPBGroupChatMessage : ACGPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 谁发送的 */
@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite, strong, null_resettable) ACGPBInt64Array *msgIdArray;
/** The number of items in @c msgIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgIdArray_Count;

@end

#pragma mark - ACPBSendGroupChatArrivalAckReq

typedef ACGPB_ENUM(ACPBSendGroupChatArrivalAckReq_FieldNumber) {
  ACPBSendGroupChatArrivalAckReq_FieldNumber_GroupChatMessageArray = 1,
};

/**
 * 群聊送达消息回执
 **/
ACGPB_FINAL @interface ACPBSendGroupChatArrivalAckReq : ACGPBMessage

/** SendGroupChatArrivalAckReqCmdId = 0x60021030; */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACPBGroupChatMessage*> *groupChatMessageArray;
/** The number of items in @c groupChatMessageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupChatMessageArray_Count;

@end

#pragma mark - ACPBSendGroupChatArrivalAckResp

typedef ACGPB_ENUM(ACPBSendGroupChatArrivalAckResp_FieldNumber) {
  ACPBSendGroupChatArrivalAckResp_FieldNumber_ErrorCode = 1,
  ACPBSendGroupChatArrivalAckResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBSendGroupChatArrivalAckResp : ACGPBMessage

/** SendGroupChatArrivalAckRespCmdId = 0x60028030; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBSendGroupChatReadAckReq

typedef ACGPB_ENUM(ACPBSendGroupChatReadAckReq_FieldNumber) {
  ACPBSendGroupChatReadAckReq_FieldNumber_GroupChatMessageArray = 1,
};

/**
 * 群聊已读消息回执
 **/
ACGPB_FINAL @interface ACPBSendGroupChatReadAckReq : ACGPBMessage

/** SendGroupChatReadAckReqCmdId = 0x60021031; */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACPBGroupChatMessage*> *groupChatMessageArray;
/** The number of items in @c groupChatMessageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupChatMessageArray_Count;

@end

#pragma mark - ACPBSendGroupChatReadAckResp

typedef ACGPB_ENUM(ACPBSendGroupChatReadAckResp_FieldNumber) {
  ACPBSendGroupChatReadAckResp_FieldNumber_ErrorCode = 1,
  ACPBSendGroupChatReadAckResp_FieldNumber_ErrorMessage = 2,
};

ACGPB_FINAL @interface ACPBSendGroupChatReadAckResp : ACGPBMessage

/** SendGroupChatReadAckRespCmdId = 0x60028031; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - ACPBGetNewSharingGroupMessageReq

typedef ACGPB_ENUM(ACPBGetNewSharingGroupMessageReq_FieldNumber) {
  ACPBGetNewSharingGroupMessageReq_FieldNumber_GroupId = 1,
  ACPBGetNewSharingGroupMessageReq_FieldNumber_Offset = 2,
  ACPBGetNewSharingGroupMessageReq_FieldNumber_Rows = 3,
};

/**
 * 获取群新消息  只是群消息
 **/
ACGPB_FINAL @interface ACPBGetNewSharingGroupMessageReq : ACGPBMessage

/** GetNewSharingGroupMessageReqCmdId = 0x6002103B; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 客户端持有的当前消息序号偏移量 */
@property(nonatomic, readwrite) int64_t offset;

/** 取正值，表示分页请求 */
@property(nonatomic, readwrite) int32_t rows;

@end

#pragma mark - ACPBGetNewSharingGroupMessageResp

typedef ACGPB_ENUM(ACPBGetNewSharingGroupMessageResp_FieldNumber) {
  ACPBGetNewSharingGroupMessageResp_FieldNumber_ErrorCode = 1,
  ACPBGetNewSharingGroupMessageResp_FieldNumber_ErrorMessage = 2,
  ACPBGetNewSharingGroupMessageResp_FieldNumber_Seqno = 3,
  ACPBGetNewSharingGroupMessageResp_FieldNumber_DialogMessageArray = 4,
  ACPBGetNewSharingGroupMessageResp_FieldNumber_Reference = 5,
  ACPBGetNewSharingGroupMessageResp_FieldNumber_EndOffset = 6,
};

ACGPB_FINAL @interface ACPBGetNewSharingGroupMessageResp : ACGPBMessage

/** GetNewSharingGroupMessageRespCmdId = 0x6002803B; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** 服务器端最新的消息序号 */
@property(nonatomic, readwrite) int64_t seqno;

/** 改群有新消息的会话对应的消息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACPBDialogMessage*> *dialogMessageArray;
/** The number of items in @c dialogMessageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dialogMessageArray_Count;

/** map<msgIdReferenced, ReferenceDialogMessage> 引用的消息信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, ACPBReferenceDialogMessage*> *reference;
/** The number of items in @c reference without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger reference_Count;

/** 此次拉取消息的endOffset */
@property(nonatomic, readwrite) int64_t endOffset;

@end

#pragma mark - ACPBDeleteGroupChatDialogReq

typedef ACGPB_ENUM(ACPBDeleteGroupChatDialogReq_FieldNumber) {
  ACPBDeleteGroupChatDialogReq_FieldNumber_GroupId = 1,
};

/**
 * 删除历史记录 请求
 **/
ACGPB_FINAL @interface ACPBDeleteGroupChatDialogReq : ACGPBMessage

/** DeleteGroupChatDialogReqCmdId=0x60021004; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - ACPBDeleteGroupChatDialogResp

typedef ACGPB_ENUM(ACPBDeleteGroupChatDialogResp_FieldNumber) {
  ACPBDeleteGroupChatDialogResp_FieldNumber_ErrorCode = 1,
  ACPBDeleteGroupChatDialogResp_FieldNumber_ErrorMessage = 2,
  ACPBDeleteGroupChatDialogResp_FieldNumber_Notification = 3,
};

/**
 * 删除历史记录 回复
 **/
ACGPB_FINAL @interface ACPBDeleteGroupChatDialogResp : ACGPBMessage

/** DeleteGroupChatDialogRespCmdId=0x60028004; */
@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

/** 操作后的提醒消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *notification;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
