//
//  ACMediaMessageContent.h
//  ACIMLib
//
//  Created by 子木 on 2022/6/17.
//

#import "ACMessageContent.h"

NS_ASSUME_NONNULL_BEGIN

/**
 *  \~chinese
 媒体类型消息的父类

 @discussion
 SDK 中所有媒体类型消息（图片、文件等）均继承此类。
 
 *  \~english
 The parent class of the media type message.

 @ discussion
 All media type messages (images, files, and so on) in SDK inherit this class.
 */
@interface ACMediaMessageContent : ACMessageContent

/**
 *  \~chinese
 媒体内容的本地路径（此属性必须有值）
 
 *  \~english
 The local path to the media content (this property must have a value).
 */
@property (nonatomic, copy) NSString *localPath;

/**
 *  \~chinese
 媒体内容上传服务器后的网络地址（上传成功后 SDK 会为该属性赋值）
 
 *  \~english
 The network address after the media content is uploaded to the server (SDK will assign a value to this attribute after the upload is successful).
 */
@property (nonatomic, copy) NSString *remoteUrl;

/*
 媒体内容加密key
 */
@property (nonatomic, copy) NSString *encryptKey;

/**
 *  \~chinese
 媒体内容的文件名（如不传使用 SDK 中 downloadMediaMessage 方法下载后会默认生成一个名称）
 
 *  \~english
 The file name of the media content (if not passed, a name will be generated by default after downloading using the downloadMediaMessage method in SDK).
 */
@property (nonatomic, copy) NSString *name;

@end

NS_ASSUME_NONNULL_END
